# Generated by Django 4.2.4 on 2023-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_companyprofilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofilemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofilemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
