# Generated by Django 4.2.4 on 2023-08-18 07:26

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_alter_companyprofilemodel_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofilemodel",
            name="logo",
        ),
        migrations.AddField(
            model_name="companyprofilemodel",
            name="logo_file",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/omkarmankar/DJANGO_START/jyotishi_project/jyotishi/media"
                    )
                ),
                upload_to="company",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofilemodel",
            name="gst_file",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/omkarmankar/DJANGO_START/jyotishi_project/jyotishi/media"
                    )
                ),
                upload_to="company",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofilemodel",
            name="iso_file",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/omkarmankar/DJANGO_START/jyotishi_project/jyotishi/media"
                    )
                ),
                upload_to="company",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofilemodel",
            name="pan_file",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/Users/omkarmankar/DJANGO_START/jyotishi_project/jyotishi/media"
                    )
                ),
                upload_to="company",
            ),
        ),
    ]
