# Generated by Django 4.2.5 on 2023-11-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientMgmt", "0002_alter_clientdetails_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetails",
            name="client_name",
            field=models.CharField(max_length=255),
        ),
    ]
