# Generated by Django 4.2.5 on 2023-10-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockMgmt", "0004_stockmgmt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockmgmt",
            old_name="dealer_mobile",
            new_name="dealer_mob_number",
        ),
    ]
