# Generated by Django 4.2.5 on 2023-09-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vastuMgmt", "0010_badaldisha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parinam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vastu_id", models.IntegerField()),
                ("disha_id", models.IntegerField()),
                ("parinam", models.TextField()),
                ("a_id", models.IntegerField(blank=True, null=True)),
                ("delete", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
