# Generated by Django 4.2.5 on 2023-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vastuMgmt", "0011_parinam"),
    ]

    operations = [
        migrations.CreateModel(
            name="VastuMgmt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField()),
                ("date_field", models.DateField()),
                ("vastu_id", models.IntegerField(default=0)),
                ("vastu", models.TextField()),
                ("disha_id", models.IntegerField(default=0)),
                ("disha", models.TextField()),
                ("parinam_id", models.IntegerField(default=0)),
                ("parinam", models.TextField()),
                ("badal_disha_id", models.IntegerField(default=0)),
                ("badal_disha", models.TextField()),
                ("bsn_upay_id", models.IntegerField(default=0)),
                ("bsn_upay", models.TextField()),
                ("etar_upay_id", models.IntegerField(default=0)),
                ("etar_upay", models.TextField()),
                ("vis_upay_id", models.IntegerField(default=0)),
                ("vis_upay", models.TextField()),
                ("twod_threed_upay_id", models.IntegerField(default=0)),
                ("twod_threed_upay", models.TextField()),
                ("ext_upay_id", models.IntegerField(default=0)),
                ("ext_upay", models.TextField()),
                ("vis_salla_id", models.IntegerField(default=0)),
                ("vis_salla", models.TextField()),
                ("a_id", models.IntegerField(blank=True, null=True)),
                ("delete", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
