# Generated by Django 4.2.5 on 2023-09-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vastuMgmt", "0012_vastumgmt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vastumgmt",
            name="badal_disha",
        ),
        migrations.RemoveField(
            model_name="vastumgmt",
            name="disha",
        ),
        migrations.RemoveField(
            model_name="vastumgmt",
            name="vastu",
        ),
    ]
