# Generated by Django 4.2.5 on 2023-10-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vastuMgmt", "0014_alter_vastumgmt_bsn_upay_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vastumgmt",
            name="client_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
