# Generated by Django 4.2.5 on 2023-10-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vastuMgmt", "0015_alter_vastumgmt_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vastumgmt",
            name="bsn_upay",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="bsn_upay_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="date_field",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="etar_upay",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="etar_upay_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="ext_upay",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="ext_upay_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="twod_threed_upay",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="twod_threed_upay_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="vis_salla",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="vis_salla_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="vis_upay",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="vis_upay_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
