# Generated by Django 4.2.5 on 2023-10-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vastuMgmt",
            "0016_alter_vastumgmt_bsn_upay_alter_vastumgmt_bsn_upay_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vastumgmt",
            name="disha_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="parinam",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="parinam_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vastumgmt",
            name="vastu_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
