# Generated by Django 4.2.5 on 2023-10-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vastuMgmt", "0017_alter_vastumgmt_disha_id_alter_vastumgmt_parinam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vastumgmt",
            name="badal_disha_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
