# Generated by Django 4.2.5 on 2023-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jyotishiMgmt", "0003_jyotishisalla"),
    ]

    operations = [
        migrations.CreateModel(
            name="VishesSalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jyoque_id", models.IntegerField()),
                ("vis_salla", models.CharField(max_length=2000)),
                ("a_id", models.IntegerField(blank=True, null=True)),
                ("delete", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
