# Generated by Django 4.2.5 on 2023-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jyotishiMgmt", "0004_vishessalla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jyotishiupay",
            name="jyo_upay",
            field=models.CharField(max_length=2000),
        ),
    ]
