# Generated by Django 4.2.5 on 2023-09-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jyotishiMgmt", "0010_rename_kar_salla_karmicupay_kar_upay"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KarmicUpay",
            new_name="KarmikUpay",
        ),
    ]
