# Generated by Django 4.2.5 on 2023-09-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jyotishiMgmt", "0012_jyotishimgmt"),
    ]

    operations = [
        migrations.AddField(
            model_name="jyotishimgmt",
            name="jyo_que_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jyotishimgmt",
            name="jyo_salla_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jyotishimgmt",
            name="jyo_upay_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jyotishimgmt",
            name="kar_upay_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jyotishimgmt",
            name="vis_salla_id",
            field=models.IntegerField(default=0),
        ),
    ]
