# Generated by Django 4.2.5 on 2023-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jyotishiMgmt",
            "0013_jyotishimgmt_jyo_que_id_jyotishimgmt_jyo_salla_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jyotishimgmt",
            name="jyo_salla_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="jyotishimgmt",
            name="jyo_upay_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="jyotishimgmt",
            name="kar_upay_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="jyotishimgmt",
            name="vis_salla_id",
            field=models.TextField(),
        ),
    ]
