# Generated by Django 4.2.5 on 2023-11-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientMgmt", "0002_alter_clientdetails_mobile"),
        ("jyotishiMgmt", "0015_alter_jyotishimgmt_jyo_que_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jyotishimgmt",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clientMgmt.clientdetails",
            ),
        ),
    ]
