# Generated by Django 4.2.5 on 2023-12-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billMgmt", "0002_billmgmt_product_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.IntegerField()),
                ("protype_id", models.IntegerField()),
                ("proname_id", models.IntegerField()),
                ("comname_id", models.IntegerField()),
                (
                    "product_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product_units",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("product_quantity", models.IntegerField()),
                (
                    "sell_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ret_validity", models.CharField(max_length=100)),
                (
                    "ret_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ret_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("exc_validity", models.CharField(max_length=100)),
                (
                    "exc_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exc_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("a_id", models.IntegerField(blank=True, null=True)),
                ("delete", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="billmgmt",
            old_name="exc_amount",
            new_name="total_bill_amount",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="comname_id",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="exc_percentage",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="exc_validity",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="product_quantity",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="product_units",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="product_weight",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="proname_id",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="protype_id",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="ret_amount",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="ret_percentage",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="ret_validity",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="sell_amount",
        ),
        migrations.RemoveField(
            model_name="billmgmt",
            name="total_amount",
        ),
        migrations.AlterField(
            model_name="billmgmt",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
